config/routes.rb
IkantamTest::Application.routes.draw do
  devise_for :users
  root 'index#index'
  resources :materials

end

app/models/material.rb
class Material
  include Mongoid::Document
  include Mongoid::Paperclip
  belongs_to :user
  field :file
  field :user_id
  has_mongoid_attached_file :file
  validates :file, presence: true
  validates_attachment_content_type :file, content_type: %w(image/jpeg image/jpg image/png application/pdf)
end

app/models/user.rb
class User
  include Mongoid::Document
  has_many :materials
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index

  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @materials =  Material.order('id DESC').all
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)

    if @material.save
      redirect_to materials_path
    else
      render :new
    end
  end

  def show
    @material = Material.find(params[:id])
  end

  private
  def material_params
    params.require(:material).permit(:file, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Ikantam"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Ikantam
          .container.nav-collapse
            %ul.nav
              %li= link_to 'Upload File', new_material_path
              %li= link_to "Show user's files", materials_path

    .container

      .row.page
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li= link_to 'Upload File', new_material_path
              %li= link_to "Show user's files", materials_path
        .span9
          = bootstrap_flash
          = yield
    
      %footer
        %p
          Artyom Lagun's Test for iKantam, February 2014

app/views/materials/_form.html.haml
= form_for @material, :html => {:class => 'form-horizontal'} do |f|
  .control-group
    = f.label :file, :class => 'control-label'
    .controls
      = f.file_field :file, :class => 'text_field'
  .control-group
    = f.hidden_field :user_id, :value => current_user.id
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'

app/views/materials/_material.html.haml
.well.content
  .row
    .span2
      %h4
        ID: #{material.id}
        File:
      - if material.file_content_type == 'image/jpeg' || material.file_content_type == 'image/jpg' || material.file_content_type == 'image/png'
        = image_tag "#{material.file.url}"
        = link_to 'Download', "#{material.file.url}"
      - else
        = link_to "#{material.file_file_name}", "#{material.file.url}"

app/views/materials/index.html.haml
%h3
  User's files

= render @materials

app/views/materials/new.html.haml
%h3
  Upload new file

= render 'form'

app/views/materials/show.html.haml
%h3
  File: #{@material.file.url}